spring:
  datasource:
     url: jdbc:mysql://localhost:3306/mybd?useSSL=false&characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
     hikari:
       connection-timeout: 60000
       maximum-pool-size: 5
  jpa:
   hibernate:
    ddl-auto: create-drop